### ISSUE TITLE
Automation Checklist

### ISSUE THREAD

**Issue by vade** [Synopsis/Synopsis-Analyzer#83]
* [x] Basic watch folder support
* [x] Basic output folder support
* [x] FSEvent mechanism to be notified when local and remote mounted folders change
* [x] Internal state tracking of folder deltas and change sets to kick off analysis sessions
* [x] Automation infrastructure folder supports duplicating hierarchy of folders. Ie source sub folders relative to watch folder are duplicated into output folder.
